export const initialdata = [
  {
    userId: 1,
    id: 1,
    title: "quidem molestiae enim",
    product: "product 1",
    price: 2000,
    category: "sneaker",
  },
  {
    userId: 1,
    id: 2,
    title: "sunt qui excepturi placeat culpa",
    product: "product 2",
    price: 3000,
    category: "sneaker",
  },
  {
    userId: 1,
    id: 3,
    title: "omnis laborum odio",
    product: "product 3",
    price: 1000,
    category: "sneaker",
  },
  {
    userId: 1,
    id: 4,
    title: "non esse culpa molestiae omnis sed optio",
    product: "product 4",
    price: 4000,
    category: "sneaker",
  },
  {
    userId: 1,
    id: 5,
    title: "eaque aut omnis a",
    product: "product 5",
    price: 200,
    category: "sneaker",
  },
  {
    userId: 1,
    id: 6,
    title: "natus impedit quibusdam illo est",
    product: "product 6",
    price: 600,
    category: "sneaker",
  },
  {
    userId: 1,
    id: 7,
    title: "quibusdam autem aliquid et et quia",
    product: "product 7",
    price: 900,
    category: "winter cloth",
  },
  {
    userId: 1,
    id: 8,
    title: "qui fuga est a eum",
    product: "product 8",
    price: 200,
    category: "winter cloth",
  },
  {
    userId: 1,
    id: 9,
    title: "saepe unde necessitatibus rem",
    product: "product 9",
    price: 9300,
    category: "winter cloth",
  },
  {
    userId: 1,
    id: 10,
    title: "distinctio laborum qui",
    product: "product 10",
    price: 390,
    category: "winter cloth",
  },
];
